<?php

namespace WTS_EAE\Modules\Chart;

use WTS_EAE\Base\Module_Base;

class Module extends Module_Base{

    public function get_widgets() {
        return [
            'Chart',
        ];
    }

    public function get_name() {
        return 'eae-chart';
    }

    public function get_title() {

        return __('Chart', 'wts-eae');

    }

    function add_dependent_js_css() {
        parent::add_dependent_js_css(); // TODO: Change the autogenerated stub
        wp_enqueue_script( 'eae-chart');
    }
}